"""Generating the model card from the run that produced the model.

**Generated, not written by hand.** A hand-written card drifts from the run the
moment either changes, and a card that disagrees with its own metrics is worse
than none — it is a document that looks authoritative and is wrong. Everything
quoted here comes from the result object.

The limitations section is the part that matters most and is the part a generated
document is least likely to include, so it is written out in full rather than
summarised.
"""

from __future__ import annotations

from sentinelflow_scoring.training.evaluation import ALERT_BUDGET, FBETA, Metrics
from sentinelflow_scoring.training.pipeline import (
    MINIMUM_MARGIN_OVER_RULES,
    RULES_BASELINE,
    TrainingResult,
)


def render(result: TrainingResult, model_version: str, dataset_profile: str, examples: int) -> str:
    """The model card for a run that selected a model."""
    chosen = result.selection.model
    if chosen is None:  # pragma: no cover - the caller checks first
        raise ValueError("No model was selected, so there is no model card to write")

    return "\n".join(
        [
            f"# Model card — {chosen.name} {model_version}",
            "",
            "> Generated by `sentinelflow_scoring.training`. Do not edit by hand: a card that has",
            "> drifted from the run that produced it is a document that looks authoritative and is",
            "> wrong. Regenerate it instead.",
            "",
            "## What this model is",
            "",
            f"{chosen.description}",
            "",
            "It estimates the probability that a transaction belongs to a **planted suspicious",
            "shape** in SentinelFlow's synthetic dataset. That is not the same proposition as",
            '"this transaction is fraud", and nothing here supports the second one.',
            "",
            "The value is served on the contract's 0-to-100 `modelScore` scale, which",
            "`contracts/openapi/sentinelflow-scoring.yaml` states is **not** a probability. The",
            "underlying estimate is calibrated so that one alerting threshold means the same thing",
            "across model versions and against a rules-only degraded assessment (ADR-0008 §4); the",
            "rescale onto 0-to-100 is fixed and monotone, so it stays calibrated.",
            "",
            "## Intended use, and what it is not for",
            "",
            "- **Intended:** demonstrating an end-to-end fraud-operations pipeline on synthetic",
            "  data, in an educational portfolio project.",
            "- **Not intended:** any real financial decision, any real customer, any regulatory or",
            "  compliance purpose. It is not a production fraud-decision engine and must never be",
            "  described as one.",
            "",
            "## Training data",
            "",
            f"- Profile `{dataset_profile}`, {examples} labelled examples.",
            "- **Entirely synthetic.** No real or realistic personal data of any kind.",
            "- Labels are the generator's own planted shapes, recovered through an offline export;",
            "  they never enter the operational schema (ADR-0010 §1).",
            "",
            "## How it was evaluated",
            "",
            "- **Split:** group-disjoint by account **and** time-ordered. An account is entirely",
            "  in training or entirely in the holdout, and the holdout keeps only transactions",
            f"  at or after `{result.split.holdout_cutoff}`.",
            f"- **Training rows:** {result.split.train.size}. **Holdout rows:**"
            f" {result.split.test.size}.",
            f"- **Operating point:** `{_threshold(chosen.threshold)}` on the 0-to-100 scale,",
            f"  chosen so the alert volume matches a review budget of {ALERT_BUDGET:.1%} of scored",
            "  transactions, from out-of-fold scores on the training rows and never from the",
            "  holdout.",
            "",
            "  **Quoted at full precision deliberately.** The score distribution is heavily",
            "  saturated — see the limitations — so rounding this to two decimals can produce a",
            "  number that alerts on nothing at all. An earlier version of this card did exactly",
            f"  that, printing `100.00` for a threshold of `{_threshold(chosen.threshold)}`.",
            "",
            "### Headline metrics, on the holdout",
            "",
            "**PR-AUC is the headline. Accuracy is not reported at all** — under this class",
            'imbalance a model answering "not suspicious" to everything scores extremely well on',
            "it, and a number that exists gets quoted.",
            "",
            _metrics_table(chosen.name, chosen.holdout, result.rules),
            "",
            "### Recall by planted shape",
            "",
            "An aggregate recall hides which patterns are found. These are the ones that matter.",
            "",
            _recall_table(chosen.holdout),
            "",
            "## Why this model and not another",
            "",
            result.selection.reason,
            "",
            "The rule was fixed in ADR-0010 §5 before any of it was measured: a model ships only",
            f"if it beats the rules baseline by at least {MINIMUM_MARGIN_OVER_RULES:.2f}",
            "PR-AUC, and",
            "a gap inside the cross-validation fold spread is fold noise and goes to the simpler",
            "model.",
            "",
            "**The baseline is the ruleset `apps/api` actually runs**, version",
            f"`{result.rules_version}`, which scored every example as it was exported. It is not a",
            "Python reimplementation of those rules: two implementations would drift, and the",
            "drift would present as a model beating a baseline nobody runs.",
            "",
            "`IsolationForest` was compared and is **not eligible to ship**: its anomaly score is",
            "unbounded and dataset-relative, so giving it a stable 0-to-100 meaning would require",
            "calibrating against the labels it was included for being able to ignore.",
            "",
            "## Limitations",
            "",
            "**Every number above is measured on synthetic data whose labels are the generator's",
            "own planted shapes.** What is measured is the pipeline's ability to recover patterns",
            "that were deliberately put there — not its ability to detect fraud. It is not",
            "comparable to any published benchmark and does not reproduce any organisation's",
            "reported figures.",
            "",
            f"- **The alert budget of {ALERT_BUDGET:.1%} is an assumption, not a measurement.** It",
            "  stands for a review capacity nobody has measured here. Every precision, recall and",
            "  false-positive figure above is *at that budget* and moves if it moves.",
            "- **`balanceDrainRatio` is measured against a balance that never changes.**",
            "  Nothing in SentinelFlow mutates an account balance, so each transaction's drain",
            "  ratio is",
            "  against the account's opening balance rather than a running one. An `ACCOUNT_DRAIN`",
            "  therefore reads as several independent partial drains rather than one cumulative",
            "  emptying; the velocity and one-hour-sum features actually carry that shape.",
            "- **Rapid fan-in is not expressible in the data at all.** `transactions` records an",
            "  account and a merchant with no counterparty account, so that pattern is absent",
            "  rather than undetected. See `docs/data/DATA_PROVENANCE.md`.",
            "- **The holdout is small.** With a group-disjoint split the dataset is spent in",
            "  accounts rather than rows, so the confidence interval around every figure here is",
            "  wider than the number of transactions suggests.",
            "- **The score distribution is heavily saturated, and the operating point sits in",
            "  that region.** Most transactions score near zero and a small group scores within a",
            "  fraction of 100, so the threshold lands where a change of a hundredth moves recall",
            "  by a large margin. Measured on this run: thresholds of 99.99, 99.0 and 95.0 give",
            "  recalls of 0.32, 0.48 and 0.53 over the same holdout. Precision stays at 1.000",
            "  across all three, so the trade is recall against alert volume rather than against",
            "  false positives — but the sensitivity is real and a deployment should choose the",
            "  threshold from the alert volume it can absorb, not by copying this number.",
            f"- **F-beta is reported at beta={FBETA:g}**, weighting recall above precision. That",
            "  encodes an assumption about the relative cost of a missed case and a wasted review",
            "  which no measurement here supports.",
            "",
            "## Reproducing this",
            "",
            "```text",
            "make seed",
            "make export-dataset",
            "cd apps/scoring && uv run python -m sentinelflow_scoring.training",
            "```",
            "",
            "The manifest beside this card records the dataset fingerprint, the seed, the feature",
            "version, the split strategy, the hyperparameters, the environment lock hash and the",
            "artifact checksum. **The checksum proves the loaded artifact is the evaluated",
            "artifact; it does not claim byte-reproducible retraining** — joblib output",
            "depends on library build details that vary across platforms. What is",
            "reproducible is the metrics.",
            "",
        ]
    )


def _threshold(value: float) -> str:
    """A threshold with enough significant figures to be usable.

    Two decimals is not enough. A calibrated model over separable data pushes its
    top scores to within a fraction of 100, so ``99.99986…`` rounds to ``100.00``
    — and a reader who applies ``100.00`` alerts on nothing. Ten significant
    figures is more than anyone wants to read and exactly what the number needs.
    """
    return f"{value:.10g}"


def _metrics_table(name: str, model: Metrics, rules: Metrics) -> str:
    rows = [
        ("PR-AUC (average precision)", model.pr_auc, rules.pr_auc, "higher is better"),
        ("Precision at the operating point", model.precision, rules.precision, ""),
        ("Recall at the operating point", model.recall, rules.recall, ""),
        ("F1", model.f1, rules.f1, ""),
        (f"F-beta (beta={FBETA:g})", model.fbeta, rules.fbeta, ""),
        ("False-positive rate", model.false_positive_rate, rules.false_positive_rate, "lower"),
        ("Alert rate", model.alert_rate, rules.alert_rate, "vs the budget"),
        ("Brier score", model.brier, rules.brier, "lower is better"),
        ("ROC-AUC (secondary only)", model.roc_auc, rules.roc_auc, ""),
    ]

    lines = [
        f"| Metric | {name} | {RULES_BASELINE} | Note |",
        "| ------ | ------ | ---------------- | ---- |",
    ]
    lines.extend(f"| {label} | {a:.4f} | {b:.4f} | {note} |" for label, a, b, note in rows)
    lines.append("")
    lines.append(
        f"Confusion matrix at the operating point: {model.confusion.true_positives} true positives,"
        f" {model.confusion.false_positives} false positives,"
        f" {model.confusion.false_negatives} false negatives,"
        f" {model.confusion.true_negatives} true negatives"
        f" ({model.positives} positives and {model.negatives} negatives in the holdout)."
    )
    return "\n".join(lines)


def _recall_table(model: Metrics) -> str:
    if not model.recall_by_label:
        return "_No planted shapes in the holdout to report on._"

    lines = ["| Planted shape | Recall at the operating point |", "| ------------- | ----- |"]
    lines.extend(f"| `{label}` | {value:.4f} |" for label, value in model.recall_by_label.items())
    return "\n".join(lines)
