#!/usr/bin/env bash
#
# Replays a named operational scenario against the running local stack, and
# reports what the pipeline actually did with it.
#
# WHAT THIS IS, AND WHAT IT IS NOT
#
# The transaction *shapes* section 8.3 lists - velocity bursts, amount spikes,
# card testing, improbable journeys, balance drains, off-hours purchases - are
# generated by `make seed`, which lays them over the seeded parties and writes
# them through the same validation, the same idempotency constraint and the same
# outbox row as a posted transaction. Replaying them here would be a second
# implementation of something that already exists.
#
# What section 8.3 lists and nothing else produces is the *operational*
# scenarios: a temporary scoring-service outage, and a malformed event reaching
# the dead-letter path. Neither could be demonstrated until an assessment
# workflow existed to degrade and a handler existed to refuse. Both can now, so
# this is what `make replay` replays.
#
# The HTTP endpoint section 10 lists - POST /api/v1/scenarios/{name}/replay - is
# a different thing on a different schedule: it is API surface, it needs the
# authorization and the rate limiting that arrive in later phases, and building
# it now would mean shipping an unbounded replay endpoint with no role behind
# it. This script is the operator-facing half and says so.
#
# EVERYTHING HERE IS SYNTHETIC. No real institution's data, rules or thresholds
# are involved, and nothing this prints is a claim about any real system.
#
# Usage: scripts/dev/replay.sh [scoring-outage|poison-event|all]

set -euo pipefail

SCENARIO="${1:-all}"
API_BASE="${SENTINELFLOW_API_BASE:-http://localhost:8080}"
# One run id per invocation, so idempotency keys never collide with an earlier
# run against the same database. Replaying twice must post twice, not silently
# return the first run's transactions.
RUN_ID="$(date -u +%Y%m%dT%H%M%SZ)-$$"
# Bounded, deliberately. An unbounded replay is a denial-of-service primitive
# against a developer's own laptop, and four transactions is enough to see a
# degraded assessment and a scored one side by side.
TRANSACTIONS_PER_PHASE=4

say() { printf '\n== %s\n' "$1"; }
note() { printf '   %s\n' "$1"; }

fail() {
    printf '\n   FAILED: %s\n' "$1" >&2
    exit 1
}

compose() { docker compose "$@"; }

# A read-only query against the demo database. Reading, never editing: a replay
# that edited rows behind the pipeline would be demonstrating the script rather
# than the system.
query() {
    compose exec -T postgres psql -U "${POSTGRES_USER:-sentinelflow}" \
        -d "${POSTGRES_DB:-sentinelflow}" -At -c "$1"
}

require_stack() {
    say "Checking the stack"
    if ! compose ps --status running --services 2>/dev/null | grep -qx api; then
        fail "the api service is not running. Start the stack with 'make up' first."
    fi
    # The crash loop worth checking for by name: leaving an export or a seed flag
    # set on the service makes it fail startup, restart, and fail again, and
    # every symptom after that is a symptom of the wrong thing.
    local state
    state="$(compose ps --format '{{.Service}} {{.Status}}' | awk '$1 == "api" {$1=""; print}')"
    case "$state" in
    *Restarting*) fail "the api container is restarting: ${state}. See PROJECT_STATE.md on the export flag." ;;
    esac
    curl -fsS "${API_BASE}/actuator/health/readiness" >/dev/null ||
        fail "the api is not ready at ${API_BASE}"
    note "api is up and ready at ${API_BASE}"
}

# An account and a merchant that already exist. The seed created them; picking
# them from the database rather than hard-coding a reference means this works
# against any profile.
pick_account() { query "SELECT account_reference FROM accounts ORDER BY account_reference LIMIT 1"; }
pick_merchant() { query "SELECT merchant_reference FROM merchants ORDER BY merchant_reference LIMIT 1"; }

post_transaction() {
    local account="$1" merchant="$2" key="$3" amount="$4"
    curl -fsS -X POST "${API_BASE}/api/v1/transactions" \
        -H 'Content-Type: application/json' \
        -d "{
              \"idempotencyKey\": \"${key}\",
              \"accountReference\": \"${account}\",
              \"merchantReference\": \"${merchant}\",
              \"type\": \"PURCHASE\",
              \"channel\": \"CARD_NOT_PRESENT\",
              \"amount\": {\"value\": \"${amount}\", \"currency\": \"GBP\"},
              \"originCountry\": \"GB\",
              \"occurredAt\": \"$(date -u +%Y-%m-%dT%H:%M:%SZ)\"
            }" |
        sed -n 's/.*"transactionId":"\([^"]*\)".*/\1/p'
}

# Posts a phase's worth of transactions and prints the ids it created.
post_phase() {
    local account="$1" merchant="$2" label="$3"
    local index id
    for index in $(seq 1 "${TRANSACTIONS_PER_PHASE}"); do
        id="$(post_transaction "$account" "$merchant" "replay-${RUN_ID}-${label}-${index}" "$((120 + index * 37)).00")"
        [ -n "$id" ] || fail "the API accepted no transaction for ${label}/${index}"
        printf '%s\n' "$id"
    done
}

# The outbox publishes on a poll interval and the consumer then scores, so
# nothing here is instant. Bounded, and it says what it was waiting for.
await_assessments() {
    local ids="$1" expected="$2" waited=0
    local list
    list="$(printf "'%s'," $ids | sed 's/,$//')"
    while [ "$waited" -lt 60 ]; do
        if [ "$(query "SELECT count(*) FROM risk_assessments WHERE transaction_id IN (${list})")" = "$expected" ]; then
            return 0
        fi
        sleep 2
        waited=$((waited + 2))
    done
    fail "only $(query "SELECT count(*) FROM risk_assessments WHERE transaction_id IN (${list})") of ${expected} transactions were assessed within 60s"
}

report_assessments() {
    local ids="$1" list
    list="$(printf "'%s'," $ids | sed 's/,$//')"
    query "
        SELECT '   ' || substr(t.transaction_reference, 1, 12)
               || '  final=' || rpad(r.final_score::text, 6, ' ')
               || '  band=' || rpad(r.risk_band, 8, ' ')
               || '  ' || CASE WHEN r.degraded
                               THEN 'DEGRADED (rules only, model unavailable)'
                               ELSE 'scored, model ' || r.model_version END
          FROM risk_assessments r
          JOIN transactions t ON t.id = r.transaction_id
         WHERE r.transaction_id IN (${list})
         ORDER BY t.transaction_reference"
}

# ---------------------------------------------------------------------------
# Scenario: a temporary scoring-service outage
# ---------------------------------------------------------------------------
#
# ADR-0008 section 3 says an unreachable scoring service degrades an assessment
# rather than losing it or rejecting the transaction. That is a claim about
# behaviour under failure, and the only honest way to show it is to cause the
# failure.

replay_scoring_outage() {
    local account merchant degraded_ids scored_ids
    account="$(pick_account)"
    merchant="$(pick_merchant)"
    [ -n "$account" ] && [ -n "$merchant" ] ||
        fail "no seeded account or merchant found. Run 'make seed' first."

    say "Scenario: temporary scoring-service outage"
    note "Stopping the scoring service. Ingestion is unaffected by design:"
    note "the transaction is accepted, committed and published before scoring runs."
    compose stop scoring >/dev/null

    # The client's own budget is three attempts inside ten seconds, and its
    # breaker opens after five consecutive failures - so the first few of these
    # pay the timeout and the rest degrade immediately. That is the breaker
    # doing the job it exists for, and it is visible in how fast this returns.
    degraded_ids="$(post_phase "$account" "$merchant" outage)"
    note "Posted ${TRANSACTIONS_PER_PHASE} transactions with scoring down."
    await_assessments "$degraded_ids" "$TRANSACTIONS_PER_PHASE"
    report_assessments "$degraded_ids"

    say "Restarting the scoring service"
    compose up -d --wait --wait-timeout 180 scoring >/dev/null
    note "Waiting for the circuit breaker's open window to elapse before the next call."
    # The breaker stays open for its configured duration after the service is
    # healthy again. Posting inside that window would produce degraded
    # assessments and look like the restart had not worked.
    sleep 32

    scored_ids="$(post_phase "$account" "$merchant" recovered)"
    note "Posted ${TRANSACTIONS_PER_PHASE} transactions with scoring back up."
    await_assessments "$scored_ids" "$TRANSACTIONS_PER_PHASE"
    report_assessments "$scored_ids"

    say "What that showed"
    note "No transaction was rejected and no assessment was lost."
    note "A degraded assessment is a real answer from the rule baseline, and it"
    note "says so: degraded = true, no model score, no model version."
}

# ---------------------------------------------------------------------------
# Scenario: a malformed event reaching the dead-letter path
# ---------------------------------------------------------------------------
#
# ADR-0006 section 4 classifies a message that will fail identically on every
# delivery as non-retryable, so it goes straight to the dead-letter topic rather
# than blocking its partition. Nothing that arrives through the API can produce
# one, which is why these are published directly onto the topic - which is what
# a corrupted or mis-routed producer looks like from the consumer's side.
#
# TWO RECORDS, BECAUSE THERE ARE TWO OUTCOMES AND ONLY ONE OF THEM IS A DEAD
# LETTER.
#
# The first is a well-formed envelope this build cannot handle: schemaVersion 99
# on a topic that carries v1. It is dead-lettered, with its failure class, its
# source topic and its offset.
#
# The second is not a readable envelope at all. It is deliberately NOT
# dead-lettered: the DLQ schema requires a valid envelope, and ADR-0006 section 4
# forbids copying unsanitised content onto an operational topic. It is logged
# with its coordinates and counted under sentinelflow_consumer_undeliverable_total,
# and the original bytes stay readable at those coordinates for as long as the
# topic's retention holds them. Showing only the first would leave the impression
# that everything unparseable ends up on the dead-letter topic, which is exactly
# the wrong thing for an operator to believe.

replay_poison_event() {
    local before after undeliverable_before undeliverable_after
    say "Scenario: a malformed event reaching the dead-letter path"

    before="$(dlq_depth)"
    undeliverable_before="$(undeliverable_count)"

    note "Publishing a well-formed envelope at a schema version this build does not read."
    publish_raw "$(printf '{"eventId":"%s","eventType":"transaction.created","schemaVersion":99,' "$(uuid)")$(
        printf '"occurredAt":"%s","producer":"sentinelflow-api","correlationId":"%s","traceId":null,' \
            "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$(uuid)"
    )$(printf '"aggregateType":"transaction","aggregateId":"%s","payload":{}}' "$(uuid)")"

    note "Waiting for the dead-letter topic to record it."
    local waited=0
    while [ "$waited" -lt 40 ]; do
        after="$(dlq_depth)"
        if [ "$after" -gt "$before" ]; then
            note "Dead-letter topic went from ${before} to ${after} records."
            break
        fi
        sleep 2
        waited=$((waited + 2))
    done
    [ "$after" -gt "$before" ] || fail "no dead-letter record appeared within 40s"

    note ""
    note "Publishing a record that is not a readable envelope at all."
    publish_raw 'this is not json'

    note "Waiting for the undeliverable counter to move."
    waited=0
    while [ "$waited" -lt 40 ]; do
        undeliverable_after="$(undeliverable_count)"
        if [ "$undeliverable_after" != "$undeliverable_before" ]; then
            note "sentinelflow_consumer_undeliverable_total went from ${undeliverable_before} to ${undeliverable_after}."
            break
        fi
        sleep 2
        waited=$((waited + 2))
    done
    [ "$undeliverable_after" != "$undeliverable_before" ] ||
        fail "the undeliverable counter did not move within 40s"

    if [ "$(dlq_depth)" -gt "$after" ]; then
        fail "an unreadable record reached the dead-letter topic, which ADR-0006 section 4 forbids"
    fi

    say "What that showed"
    note "The first record was classified once, not retried five times, and the"
    note "partition behind it kept moving. Its dead-letter record carries the"
    note "failure class, the source topic and the offset."
    note "The second was NOT copied onto the dead-letter topic, because the DLQ"
    note "schema requires a valid envelope and unsanitised content may not be"
    note "republished. It is counted and logged with its coordinates instead."
}

uuid() {
    # No uuidgen on every machine, and a v4 from /dev/urandom is enough for a
    # record that exists to be rejected.
    # Fifteen bytes, not sixteen: the version and variant nibbles are written by
    # the substitution rather than taken from the stream, so the pattern consumes
    # 8+4+3+3+12 = 30 hex characters and the result is exactly 32. Reading
    # sixteen left two characters unconsumed and appended, and the record then
    # failed as "not a readable envelope" rather than as the unsupported schema
    # version it exists to demonstrate - which is a scenario script quietly
    # demonstrating the wrong thing.
    od -An -tx1 -N15 /dev/urandom |
        tr -d ' \n' |
        sed -E 's/(.{8})(.{4})(.{3})(.{3})(.{12})/\1-\2-4\3-8\4-\5/'
}

publish_raw() {
    printf 'replay-%s:%s\n' "$RUN_ID" "$1" |
        compose exec -T kafka /opt/kafka/bin/kafka-console-producer.sh \
            --bootstrap-server localhost:9092 \
            --topic transaction.created.v1 \
            --property 'parse.key=true' \
            --property 'key.separator=:' >/dev/null
}

# The counter the consumer increments for a record it can neither handle nor
# dead-letter. Read from the API's own Prometheus endpoint rather than inferred.
undeliverable_count() {
    curl -fsS "${API_BASE}/actuator/prometheus" |
        awk '/^sentinelflow_consumer_undeliverable_total/ { total += $NF } END { print total + 0 }'
}

# The dead-letter topic's end offsets, summed.
#
# kafka-get-offsets.sh rather than kafka-run-class.sh with
# kafka.tools.GetOffsetShell: the class moved package in Kafka 4 and the wrapper
# script is the supported entry point. Found by running this against the 4.2.1
# broker the stack actually uses, where the old form fails with
# ClassNotFoundException - and silently, because the failure arrived as an empty
# string rather than as a non-zero exit through a pipe.
dlq_depth() {
    local output
    output="$(compose exec -T kafka /opt/kafka/bin/kafka-get-offsets.sh \
        --bootstrap-server localhost:9092 --topic transaction.processing.dlq.v1 2>/dev/null || true)"
    [ -n "$output" ] || fail "could not read the dead-letter topic's offsets"
    printf '%s\n' "$output" | awk -F: '{ total += $3 } END { print total + 0 }'
}

# ---------------------------------------------------------------------------

require_stack

case "$SCENARIO" in
scoring-outage) replay_scoring_outage ;;
poison-event) replay_poison_event ;;
all)
    replay_scoring_outage
    replay_poison_event
    ;;
*)
    fail "unknown scenario '${SCENARIO}'. Choose scoring-outage, poison-event, or all."
    ;;
esac

say "Done"
note "Every transaction, account and merchant involved is synthetic."
note "Read the assessments with: docker compose exec postgres psql -U sentinelflow -d sentinelflow"
